---
title: "test-mcda"
author: "Emily Zhou"
date: "2024-05-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Testing The MCDA Package

```{r}
Rglpk, glpkAPI, RColorBrewer, combinat, triangle, plyr,
ggplot2
```


## Testing the AHP Approach 
```{r}
alts <- c("Corsa","Clio","Fiesta","Sandero")


style <- matrix(c(1.0, 1/4, 4.0, 1/6,
4.0, 1.0, 4.0, 1/4,
1/4, 1/4, 1.0, 1/5,
6.0, 4.0, 5.0, 1.0),
nrow=length(alts), ncol=length(alts), byrow=TRUE,
dimnames=list(alts,alts))


reliability <- matrix(c(1.0, 2.0, 5.0, 1.0,
1/2, 1.0, 3.0, 2.0,
1/5, 1/3, 1.0, 1/4,
1.0, 1/2, 4.0, 1.0),
nrow=length(alts), ncol=length(alts), byrow=TRUE,
dimnames=list(alts,alts))


fuel <- matrix(c(1.0, 2.0, 4.0, 1.0,
0.5, 1.0, 3.0, 2.0,
1/4, 1/3, 1.0, 1/5,
1.0, 1/2, 5.0, 1.0),
nrow=length(alts), ncol=length(alts), byrow=TRUE,
dimnames=list(alts,alts))
```


```{r}

alternativesPairwiseComparisonsList <- list(style = style,
reliability = reliability,
fuel = fuel)

```


```{r}
crit <- c("style","reliability","fuel")
criteriaWeightsPairwiseComparisons <- matrix(c(1.0, 1/2, 3.0,
2.0, 1.0, 4.0,
1/3, 1/4, 1.0),
nrow=length(crit),
ncol=length(crit),
dimnames=list(crit,crit))
```


```{r}
AHP(criteriaWeightsPairwiseComparisons, alternativesPairwiseComparisonsList)
```

## Testing the TOPSIS Approach

```{r}


performanceTable <- matrix(c(5490,51.4,8.5,285,6500,70.6,7,
                             288,6489,54.3,7.5,290),
                           nrow=3,
                           ncol=4,
                           byrow=TRUE)

row.names(performanceTable) <- c("Corsa","Clio","Fiesta")
colnames(performanceTable) <- c("Purchase Price","Economy",
                                "Aesthetics","Boot Capacity")


weights <- c(0.35,0.25,0.25,0.15)
criteriaMinMax <- c("min", "max", "max", "max")

# positiveIdealSolutions <- c(0.179573776, 0.171636015, 0.159499658, 0.087302767)
# negativeIdealSolutions <- c(0.212610118, 0.124958799, 0.131352659, 0.085797547)
names(weights) <- colnames(performanceTable)

names(criteriaMinMax) <- colnames(performanceTable)
# names(positiveIdealSolutions) <- colnames(performanceTable)
# names(negativeIdealSolutions) <- colnames(performanceTable)
```


```{r}
overall1 <- TOPSIS(performanceTable, weights, criteriaMinMax)
overall1 # returns a vector containing the TOPSIS score for each alternative
```



